version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env

  db:
    restart: always
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: fider_pw

volumes:
  db-data:
